<<<<<<< HEAD
services:
  - type: web
    name: spiceschemdb-1
    env: python
    plan: free

    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
=======
services:
  - type: web
    name: rare-diseases-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
>>>>>>> 01ea70e (Force Python 3.11 on Render)
